name: Deploy to chosen environment

inputs:
  environment:
    description: 'Deployment environment'
    required: true
  port:
    description: 'Port the application will use'
    required: true

runs:
  using: "composite"
  steps:
    - name: Clone the app
      uses: actions/checkout@v3.5.2
      with:
        # using my repository with port fix
        #
        repository: 'mtararujs/python-greetings'
        path: python-greetings
        ref: 4e911440a9886c7c26ccbb4eb55f0bc2a5067b51
        fetch-depth: 0repository: blastoor/python-greetings
        #path: python-greetings
        
    - uses: actions/setup-node@v4
    - run: npm install pm2 -g
      shell: cmd
        
    - name: Stop current service
      working-directory: python-greetings
      run: pm2 delete greetings-app-${{ inputs.environment }} & set "errorlevel=0"
      shell: cmd

    - name: Start new service
      working-directory: python-greetings
      run: pm2 start app.py --name greetings-app-${{ inputs.environment }} -- --port ${{ inputs.port }}
      shell: cmd
