name: Install Python dependencies

runs:
  using: "composite"
  steps:
    - name: Install pip dependencies
      working-directory: python-greetings
      run: pip install -r requirements.txt
      shell: powershell
