name: Python Greetings Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: windows-latest
    name: Install required Python dependencies
    
    steps:
      - name: Checkout pipeline
        uses: actions/checkout@v3.5.2
        
      - name: Clone the app
        uses: actions/checkout@v3.5.2
        with:
          # using my repository with port fix
          repository: blastoor/python-greetings
          path: python-greetings
          
      - uses: ./.github/actions/install
      
  deploy-to-dev:
    runs-on: windows-latest
    needs: [install-pip-deps]
    name: Deploy service to development environment
    
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Deploy dev to port 7001
        uses: ./.github/actions/deploy
        with: 
          port: 7001
          environment: 'dev'
  
  tests-on-dev:
    runs-on: windows-latest
    needs: [deploy-to-dev]
    name: Test service in development environment
    
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Test development environment
        uses: ./.github/actions/test
        with: 
          environment: 'dev'

  deploy-to-staging:
    runs-on: windows-latest
    needs: [tests-on-dev]
    name: Deploy service to staging environment
    
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Deploy staging to port 7002
        uses: ./.github/actions/deploy
        with: 
          port: 7002
          environment: 'stg'
  
  tests-on-staging:
    runs-on: windows-latest
    needs: [deploy-to-staging]
    name: Test service in staging environment
    
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Test staging environment
        uses: ./.github/actions/test
        with: 
          environment: 'stg'

  deploy-to-preprod:
    runs-on: windows-latest
    needs: [tests-on-staging]
    name: Deploy service to preproduction environment
    
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Deploy preprod to port 7003
        uses: ./.github/actions/deploy
        with: 
          port: 7003
          environment: 'preprod'
  
  tests-on-preprod:
    runs-on: windows-latest
    needs: [deploy-to-preprod]
    name: Test service in preproduction environment
    
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Test preproduction environment
        uses: ./.github/actions/test
        with: 
          environment: 'preprod'

  deploy-to-prod:
    runs-on: windows-latest
    needs: [tests-on-preprod]
    name: Deploy service to production
    
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Deploy prod to port 7004
        uses: ./.github/actions/deploy
        with: 
          port: 7004
          environment: 'prod'
  
  tests-on-prod:
    runs-on: windows-latest
    needs: [deploy-to-prod]
    name: Test service in production
    
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Test production environment
        uses: ./.github/actions/test
        with: 
          environment: 'prod'
