name: Python Greetings Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    name: Install required Python dependencies
    
    steps:
      - uses: actions/checkout@v3.5.2
      
  deploy-to-dev:
    runs-on: self-hosted
    needs: [install-pip-deps]
    name: Deploy service to development environment
    
    steps:
      - uses: actions/checkout@v3.5.2
  
  tests-on-dev:
    runs-on: self-hosted
    needs: [deploy-to-dev]
    name: Test service in development environment
    
    steps:
      - uses: actions/checkout@v3.5.2

  deploy-to-staging:
    runs-on: self-hosted
    needs: [tests-on-dev]
    name: Deploy service to staging environment
    
    steps:
      - uses: actions/checkout@v3.5.2
  
  tests-on-staging:
    runs-on: self-hosted
    needs: [deploy-to-staging]
    name: Test service in staging environment
    
    steps:
      - uses: actions/checkout@v3.5.2

  deploy-to-preprod:
    runs-on: self-hosted
    needs: [tests-on-staging]
    name: Deploy service to preproduction environment
    
    steps:
      - uses: actions/checkout@v3.5.2
  
  tests-on-preprod:
    runs-on: self-hosted
    needs: [deploy-to-preprod]
    name: Test service in preproduction environment
    
    steps:
      - uses: actions/checkout@v3.5.2

  deploy-to-prod:
    runs-on: self-hosted
    needs: [tests-on-preprod]
    name: Deploy service to production
    
    steps:
      - uses: actions/checkout@v3.5.2
  
  tests-on-prod:
    runs-on: self-hosted
    needs: [deploy-to-prod]
    name: Test service in production
    
    steps:
      - uses: actions/checkout@v3.5.2
